# Generated by Django 5.1.3 on 2024-12-29 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informe', models.CharField(choices=[('movimientos', 'Informe de Movimientos'), ('inventario', 'Informe de Inventario')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'informes',
            },
        ),
    ]
